[tool.poetry]
name = "blob"
version = "0.1.0"
description = ""
authors = ["Alex <alex@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
